name: Store Image in Artifact Registry

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - name: âš™ Configure GitHub Actions
        uses: actions/checkout@v3

      - name: ğŸ›  Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7

      - name: ğŸ“¦ Build project
        run: pnpm install && pnpm run build

      - name: ğŸ· Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist/
            .dockerignore
            .gcloudignore
            app.yaml
            cloudbuild.yaml
            Dockerfile
            pnpm-lock.yaml

  deploy:
    name: Build and Push Image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: ğŸ· Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: ğŸ”’ Google Authentication
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: ğŸš§ Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: ğŸš€ Deploy to App Engine
        uses : google-github-actions/app-engine-deploy@v0
#      - name: ğŸš€ Build and publish to Artifact Registry
#        run: gcloud builds submit --config=cloudbuild.yaml --substitutions=BRANCH_NAME="${{ github.ref_name }}"