name: Build and Store Artifact Registry

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: âš™ï¸ Configure GitHub Actions
        uses: actions/checkout@v3

      - name: ğŸ›  Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7

      - name: ğŸš§ Install dependencies and Build project
        run: pnpm install && pnpm run build

      - name: ğŸ”’ Google Authentication
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: ğŸš§ Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: âš ï¸ Use gcloud CLI
        run: 'gcloud info'

      - name: ğŸš€ Build with Cloud Build
        run: 'gcloud builds submit --config=cloudbuild.yaml'